---
- name: Add Docker repository [Red Hat]
  yum_repository:
    name: docker
    description: Docker YUM repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat"

- name: Install Docker and it's dependencies [Red Hat]
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_os_family == "RedHat"

- name: Install gcc [Red Hat]
  yum:
    name: gcc
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install prerequisites [Debian]
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  when: ansible_os_family == "Debian"

- name: Import Docker GPG signing key [Debian]
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository [Debian]
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker and its dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_os_family == "Debian"

- name: Install gcc [Debian]
  apt:
    name: gcc
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"