---
- name: Download docker-compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0555'
    checksum: sha256:{{ docker_compose_shasum }}